apiVersion: gateway.k8s.aws/v1beta1
kind: LoadBalancerConfiguration
metadata:
  name: {{ .Values.private.loadBalancerConfigName | quote }}
  namespace: {{ .Values.private.namespace | quote }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  scheme: internal
  defaultTargetGroupConfiguration:
    name: {{ .Values.private.targetGroupConfigName | quote }}
  listenerConfigurations:
    - protocolPort: HTTPS:443
      defaultCertificate: {{ .Values.certificateArn | quote }}
