[[repos]]
repo = "local"

[[repos.hooks]]
id = "validate-helm"
name = "Helm lint and kubeconform"
language = "system"
entry = "scripts/validate-helm.sh"
files = '\.(yaml|yml)$'
pass_filenames = false

[[repos.hooks]]
id = "validate-manifests"
name = "kubeconform plain manifests"
language = "system"
entry = "scripts/validate-manifests.sh"
files = '\.(yaml|yml)$'
pass_filenames = false

[[repos.hooks]]
id = "trivy"
name = "Trivy"
language = "system"
entry = "trivy config --config trivy.yaml --ignorefile .trivyignore.yaml ."
files = '\.(yaml|yml)$'
pass_filenames = false

[[repos.hooks]]
id = "trivy-secrets"
name = "Trivy secret scan"
language = "system"
entry = "trivy fs ."
pass_filenames = false
