{{- range .Values.externalSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name | quote }}
  namespace: {{ $.Release.Namespace }}
spec:
  refreshPolicy: {{ .refreshPolicy | default "CreatedOnce" }}
  secretStoreRef:
    name: {{ $.Values.secretStoreName | quote }}
    kind: SecretStore
  target:
    name: {{ .targetSecretName | quote }}
    creationPolicy: {{ .targetCreationPolicy | default "Merge" }}
  data:
    {{- range .data }}
    - secretKey: {{ .secretKey | quote }}
      remoteRef:
        key: {{ .remoteKey | quote }}
        property: {{ .remoteProperty | quote }}
    {{- end }}
---
{{- end }}
