apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-dynamic-metrics-config
  namespace: {{ .Release.Namespace }}
data:
  dynamic-metrics.yaml: |
    metrics:
      - contextOptions:
          - name: sourceContext
            values: [workload-name, dns, reserved-identity]
          - name: destinationContext
            values: [workload-name, dns, reserved-identity]
          - name: labelsContext
            values: [source_namespace, destination_namespace, traffic_direction]
        name: drop
      - contextOptions:
          - name: sourceContext
            values: [workload-name, dns, reserved-identity]
          - name: destinationContext
            values: [workload-name, dns, reserved-identity]
          - name: labelsContext
            values: [source_namespace, destination_namespace, traffic_direction]
        name: tcp
      - contextOptions:
          - name: sourceContext
            values: [workload-name, dns, reserved-identity]
          - name: destinationContext
            values: [workload-name, dns, reserved-identity]
          - name: labelsContext
            values: [source_namespace, destination_namespace, traffic_direction]
        name: flow
      - contextOptions:
          - name: sourceContext
            values: [workload-name, dns, reserved-identity]
          - name: destinationContext
            values: [workload-name, dns, reserved-identity]
          - name: labelsContext
            values: [source_namespace, destination_namespace, traffic_direction]
        name: icmp
      - contextOptions:
          - name: sourceContext
            values: [workload-name, dns, reserved-identity]
          - name: destinationContext
            values: [workload-name, dns, reserved-identity]
          - name: labelsContext
            values: [source_namespace, destination_namespace]
        name: policy
      - contextOptions:
          - name: sourceContext
            values: [workload-name, dns, reserved-identity]
          - name: destinationContext
            values: [workload-name, dns, reserved-identity]
        name: port-distribution
