name: guestbook-ui
rules:
  - matches:
      - path:
          type: PathPrefix
          value: /
    backendRefKey: default
backendRefs:
  default:
    name: guestbook-ui
    port: 80
annotations:
  external-dns.alpha.kubernetes.io/scope: public
