name: podinfo
rules:
  - matches:
      - path:
          type: PathPrefix
          value: /
    backendRefKey: default
backendRefs:
  default:
    name: podinfo
    port: 9898
annotations:
  external-dns.alpha.kubernetes.io/scope: public
