apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: alloy
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: alloy
  ingress:
    # kubelet readiness probe.
    - fromEntities:
        - host
      toPorts:
        - ports:
            - port: "12345"
              protocol: TCP
  egress:
    # Pushing collected logs to loki-gateway.
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: loki
            app.kubernetes.io/component: gateway
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
