apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nested-app-crds-gateway-api
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/kubernetes-sigs/gateway-api
    path: config/crd/standard
    targetRevision: v1.5.0
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: false
      selfHeal: true
