tailscale-operator:
  operatorConfig:
    resources:
      requests:
        cpu: 15m
        memory: 100Mi
      limits:
        cpu: 15m
        memory: 100Mi
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"] # strip default Linux capabilities, none are needed
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault # apply the runtime's default seccomp profile to block risky syscalls
