tailscale-operator:
  operatorConfig:
    resources:
      requests:
        cpu: 11m
        memory: 36M
      limits:
        cpu: 11m
        memory: 36M
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"] # strip default Linux capabilities, none are needed
    podSecurityContext:
      seccompProfile:
        type: RuntimeDefault # apply the runtime's default seccomp profile to block risky syscalls
    nodeSelector:
      karpenter.sh/nodepool: elastic
    tolerations:
      - key: karpenter.sh/workload-class
        operator: Equal
        value: elastic
        effect: NoSchedule
