config:
  spec:
    destination:
      server: https://kubernetes.default.svc
    source:
      repoURL: https://github.com/ConsciousML/argocd-app-of-apps-template
      targetRevision: main

appParams: {}

applications:
  - name: crds-gateway-api
    destination:
      namespace: argocd
    syncWave: -1
  - name: crds-aws-lbc-gateway-api
    destination:
      namespace: argocd
    syncWave: -1
  - name: helm-aws-lbc
    destination:
      namespace: kube-system
    syncWave: 0
  - name: helm-guestbook
    destination:
      namespace: guestbook
    syncWave: 0
