external-dns:
  provider:
    name: aws
  txtOwnerId: "cluster"
  domainFilters: []
  triggerLoopOnEvent: true
  sources:
    - service
    - ingress
    - gateway-httproute
  registry: txt
  policy: sync
  logLevel: info
  annotationFilter: external-dns.alpha.kubernetes.io/scope=private
  extraArgs:
    aws-zone-type: private
  serviceAccount:
    name: external-dns-private
