aws-load-balancer-controller:
  # Placeholder for `helm template` to pass in CI
  clusterName: "cluster"
  region: ""
  vpcId: ""
  enableServiceMutatorWebhook: false
  serviceMonitor:
    enabled: true
