apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: default-deny
spec:
  endpointSelector:
    matchLabels:
      k8s:io.kubernetes.pod.namespace.labels.network-policy.default-deny: "true"
  enableDefaultDeny:
    ingress: true
    egress: true
